<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240809092217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE CommandeComptable (id INT AUTO_INCREMENT NOT NULL, idcmd INT DEFAULT NULL, idclient INT DEFAULT NULL, client VARCHAR(255) DEFAULT NULL, numfacture DOUBLE PRECISION DEFAULT NULL, datefacture DATE DEFAULT NULL, datecmd DATE DEFAULT NULL, numcmd INT DEFAULT NULL, quantite VARCHAR(255) DEFAULT NULL, produits LONGTEXT DEFAULT NULL, montant_ttc DOUBLE PRECISION DEFAULT NULL, frais_expedition DOUBLE PRECISION DEFAULT NULL, montant_ht DOUBLE PRECISION DEFAULT NULL, tva DOUBLE PRECISION DEFAULT NULL, moyen_paiement VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CommandeFile (id INT AUTO_INCREMENT NOT NULL, noFacture VARCHAR(255) DEFAULT NULL, noCommande VARCHAR(255) DEFAULT NULL, civilite VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, complementAdresse VARCHAR(255) DEFAULT NULL, codePostal VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, codePays VARCHAR(255) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, sejour VARCHAR(255) DEFAULT NULL, typeEnvoi VARCHAR(255) DEFAULT NULL, fichierImpression VARCHAR(255) DEFAULT NULL, produit VARCHAR(255) DEFAULT NULL, albumPhotos VARCHAR(255) DEFAULT NULL, livreSouvenirs VARCHAR(255) DEFAULT NULL, calendrier VARCHAR(255) DEFAULT NULL, polaroid VARCHAR(255) DEFAULT NULL, formatPolaroid VARCHAR(255) DEFAULT NULL, packPhoto VARCHAR(255) DEFAULT NULL, formatPackPhoto VARCHAR(255) DEFAULT NULL, coffretRigide VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Element (id INT AUTO_INCREMENT NOT NULL, idclipart INT DEFAULT NULL, idtext INT DEFAULT NULL, idpage INT DEFAULT NULL, higth VARCHAR(255) DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, x VARCHAR(255) DEFAULT NULL, y VARCHAR(255) DEFAULT NULL, rotation VARCHAR(255) DEFAULT NULL, type INT DEFAULT NULL, INDEX IDX_8EFD67A57B69AEAF (idclipart), INDEX IDX_8EFD67A5E8445667 (idtext), INDEX fk_pagecliparttext_element_idx (idpage), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MessagePartenaire (id INT AUTO_INCREMENT NOT NULL, message LONGTEXT DEFAULT NULL, nom_societe VARCHAR(255) DEFAULT NULL, nom_partenaire VARCHAR(255) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, num_tel VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, date_envoi DATE DEFAULT NULL, email_partenaire VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PageBlocktexte (id INT AUTO_INCREMENT NOT NULL, idpage INT DEFAULT NULL, idblocktext INT DEFAULT NULL, INDEX fk_block_page_idx (idpage), INDEX fk_page_block_idx (idblocktext), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Pageattachement (id INT AUTO_INCREMENT NOT NULL, idattachment INT DEFAULT NULL, idpage INT DEFAULT NULL, INDEX fk_attach_page_idx (idattachment), INDEX fk_page_attach_idx (idpage), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE adress (id INT AUTO_INCREMENT NOT NULL, numadress VARCHAR(255) DEFAULT NULL, ruevoi VARCHAR(255) DEFAULT NULL, codepostal VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, nomadrres VARCHAR(255) DEFAULT NULL, prenomadress VARCHAR(255) DEFAULT NULL, organism VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE attachement_etiquette (id INT AUTO_INCREMENT NOT NULL, id_etiquette_id INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, size INT DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, INDEX IDX_A908717B58139F25 (id_etiquette_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE attachment (id INT AUTO_INCREMENT NOT NULL, idposition INT DEFAULT NULL, idref INT DEFAULT NULL, iduser INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, idblog INT DEFAULT NULL, descreption VARCHAR(255) DEFAULT NULL, INDEX fk_attchposition_idx (idposition), INDEX fk_userphoto_idx (iduser), INDEX fk_attchref_idx (idref), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blocktext (id INT AUTO_INCREMENT NOT NULL, labelle VARCHAR(255) DEFAULT NULL, styletexte VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog (id INT AUTO_INCREMENT NOT NULL, statut INT DEFAULT NULL, iduser INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, description VARCHAR(500) DEFAULT NULL, categorie VARCHAR(500) DEFAULT NULL, INDEX fk_blog_user_idx (iduser), INDEX fk_blog_ref (statut), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_attachement (id INT AUTO_INCREMENT NOT NULL, idblog INT DEFAULT NULL, idattachement INT DEFAULT NULL, date DATETIME DEFAULT NULL, INDEX fk_at_blog_idx (idattachement), INDEX fk_blog_at_idx (idblog), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_authtoken (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, username VARCHAR(32) DEFAULT NULL, token VARCHAR(128) NOT NULL, salt VARCHAR(128) NOT NULL, lastseen DATETIME DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, useragent VARCHAR(128) DEFAULT NULL, validity DATETIME DEFAULT NULL, INDEX IDX_740AC52FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_blocks (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME DEFAULT NULL, ownerid INT DEFAULT NULL, status VARCHAR(32) NOT NULL, templatefields JSON DEFAULT NULL, title VARCHAR(256) DEFAULT NULL, content LONGTEXT DEFAULT NULL, contentlink VARCHAR(256) DEFAULT NULL, image JSON DEFAULT NULL, INDEX IDX_7B2C81B7989D9B62 (slug), INDEX IDX_7B2C81B7BE74E59A (datechanged), INDEX IDX_7B2C81B7B7805520 (datedepublish), INDEX IDX_7B2C81B7AFBA6FD8 (datecreated), INDEX IDX_7B2C81B7A5131421 (datepublish), INDEX IDX_7B2C81B77B00651C (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_cron (id INT AUTO_INCREMENT NOT NULL, interim VARCHAR(16) NOT NULL, lastrun DATETIME NOT NULL, INDEX IDX_CD38E123615F8869 (interim), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_entries (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME DEFAULT NULL, ownerid INT DEFAULT NULL, status VARCHAR(32) NOT NULL, templatefields JSON DEFAULT NULL, title VARCHAR(256) DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, body LONGTEXT DEFAULT NULL, image JSON DEFAULT NULL, video JSON DEFAULT NULL, INDEX IDX_2696ADF0989D9B62 (slug), INDEX IDX_2696ADF0BE74E59A (datechanged), INDEX IDX_2696ADF0B7805520 (datedepublish), INDEX IDX_2696ADF0AFBA6FD8 (datecreated), INDEX IDX_2696ADF0A5131421 (datepublish), INDEX IDX_2696ADF07B00651C (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_field_value (id INT AUTO_INCREMENT NOT NULL, contenttype VARCHAR(64) NOT NULL, content_id INT NOT NULL, name VARCHAR(64) NOT NULL, `grouping` INT NOT NULL, block VARCHAR(64) DEFAULT NULL, fieldname VARCHAR(255) NOT NULL, fieldtype VARCHAR(255) NOT NULL, value_string VARCHAR(255) DEFAULT NULL, value_text LONGTEXT DEFAULT NULL, value_integer INT DEFAULT NULL, value_float DOUBLE PRECISION DEFAULT NULL, value_decimal NUMERIC(18, 9) DEFAULT NULL, value_date DATE DEFAULT NULL, value_datetime DATETIME DEFAULT NULL, value_json_array JSON NOT NULL, value_boolean TINYINT(1) NOT NULL, INDEX IDX_8B31D78784A0A3ED745E1826 (content_id, contenttype), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_homepage (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME DEFAULT NULL, ownerid INT DEFAULT NULL, status VARCHAR(32) NOT NULL, templatefields JSON DEFAULT NULL, title VARCHAR(256) DEFAULT NULL, image JSON DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, contentlink VARCHAR(256) DEFAULT NULL, INDEX IDX_9D9C7FD3989D9B62 (slug), INDEX IDX_9D9C7FD3BE74E59A (datechanged), INDEX IDX_9D9C7FD3B7805520 (datedepublish), INDEX IDX_9D9C7FD3AFBA6FD8 (datecreated), INDEX IDX_9D9C7FD3A5131421 (datepublish), INDEX IDX_9D9C7FD37B00651C (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_log_change (id INT AUTO_INCREMENT NOT NULL, date DATETIME NOT NULL, ownerid INT DEFAULT NULL, title VARCHAR(256) NOT NULL, contenttype VARCHAR(128) NOT NULL, contentid INT NOT NULL, mutation_type VARCHAR(16) NOT NULL, diff JSON NOT NULL, comment VARCHAR(150) DEFAULT NULL, INDEX IDX_946F972AA9E377A (date), INDEX IDX_946F972745E1826 (contenttype), INDEX IDX_946F972B0AEEF39 (mutation_type), INDEX IDX_946F97275DAD987 (ownerid), INDEX IDX_946F972E625AE99 (contentid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_log_system (id INT AUTO_INCREMENT NOT NULL, level INT NOT NULL, date DATETIME NOT NULL, message VARCHAR(1024) NOT NULL, ownerid INT DEFAULT NULL, requesturi VARCHAR(128) NOT NULL, route VARCHAR(128) NOT NULL, ip VARCHAR(45) NOT NULL, context VARCHAR(32) NOT NULL, source JSON NOT NULL, INDEX IDX_805C16D99AEACC13 (level), INDEX IDX_805C16D975DAD987 (ownerid), INDEX IDX_805C16D9AA9E377A (date), INDEX IDX_805C16D9E25D857E (context), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_pages (id INT AUTO_INCREMENT NOT NULL, categorie INT DEFAULT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME DEFAULT NULL, ownerid INT DEFAULT NULL, status VARCHAR(32) NOT NULL, templatefields JSON DEFAULT NULL, title VARCHAR(256) DEFAULT NULL, image JSON DEFAULT NULL, teaser LONGTEXT DEFAULT NULL, body LONGTEXT DEFAULT NULL, template VARCHAR(256) DEFAULT NULL, INDEX IDX_31AF1BC8989D9B62 (slug), INDEX IDX_31AF1BC8BE74E59A (datechanged), INDEX IDX_31AF1BC8B7805520 (datedepublish), INDEX IDX_31AF1BC8AFBA6FD8 (datecreated), INDEX IDX_31AF1BC8A5131421 (datepublish), INDEX IDX_31AF1BC87B00651C (status), INDEX bolt_taxonomy (categorie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_relations (id INT AUTO_INCREMENT NOT NULL, from_contenttype VARCHAR(32) NOT NULL, from_id INT NOT NULL, to_contenttype VARCHAR(32) NOT NULL, to_id INT NOT NULL, INDEX IDX_4C524BC3EA11294378CED90B (from_contenttype, from_id), INDEX IDX_4C524BC35ACD264530354A65 (to_contenttype, to_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_showcases (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(128) NOT NULL, datecreated DATETIME NOT NULL, datechanged DATETIME NOT NULL, datepublish DATETIME DEFAULT NULL, datedepublish DATETIME DEFAULT NULL, ownerid INT DEFAULT NULL, status VARCHAR(32) NOT NULL, templatefields JSON DEFAULT NULL, title VARCHAR(256) DEFAULT NULL, html LONGTEXT DEFAULT NULL, textarea LONGTEXT DEFAULT NULL, markdown LONGTEXT DEFAULT NULL, geolocation JSON DEFAULT NULL, embed JSON DEFAULT NULL, video JSON DEFAULT NULL, image JSON DEFAULT NULL, imagelist JSON DEFAULT NULL, file VARCHAR(256) DEFAULT NULL, filelist JSON DEFAULT NULL, checkbox TINYINT(1) NOT NULL, datetime DATETIME DEFAULT NULL, date DATE DEFAULT NULL, integerfield INT NOT NULL, floatfield DOUBLE PRECISION NOT NULL, selectfield LONGTEXT DEFAULT NULL, multiselect JSON DEFAULT NULL, selectentry LONGTEXT DEFAULT NULL, INDEX IDX_C5F751E8989D9B62 (slug), INDEX IDX_C5F751E8BE74E59A (datechanged), INDEX IDX_C5F751E8B7805520 (datedepublish), INDEX IDX_C5F751E8FD4718AE (integerfield), INDEX IDX_C5F751E8AFBA6FD8 (datecreated), INDEX IDX_C5F751E8A5131421 (datepublish), INDEX IDX_C5F751E87B00651C (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_taxonomy (id INT AUTO_INCREMENT NOT NULL, content_id INT NOT NULL, contenttype VARCHAR(32) NOT NULL, taxonomytype VARCHAR(32) NOT NULL, slug VARCHAR(64) NOT NULL, name VARCHAR(64) NOT NULL, sortorder INT NOT NULL, INDEX IDX_ABAA120084A0A3ED (content_id), INDEX IDX_ABAA1200FE2A268F (taxonomytype), INDEX IDX_ABAA1200FEA3B3F9 (sortorder), INDEX IDX_ABAA1200745E1826 (contenttype), INDEX IDX_ABAA1200989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bolt_users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(32) NOT NULL, password VARCHAR(128) NOT NULL, email VARCHAR(254) NOT NULL, lastseen DATETIME DEFAULT NULL, lastip VARCHAR(45) DEFAULT NULL, displayname VARCHAR(32) NOT NULL, stack JSON NOT NULL, enabled TINYINT(1) DEFAULT 1 NOT NULL, shadowpassword VARCHAR(128) DEFAULT NULL, shadowtoken VARCHAR(128) DEFAULT NULL, shadowvalidity DATETIME DEFAULT NULL, failedlogins INT NOT NULL, throttleduntil DATETIME DEFAULT NULL, roles JSON NOT NULL, INDEX IDX_5585B5450F9BB84 (enabled), UNIQUE INDEX UNIQ_5585B54F85E0677 (username), UNIQUE INDEX UNIQ_5585B54E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cart (id INT AUTO_INCREMENT NOT NULL, idsejour INT DEFAULT NULL, nbconsomateur INT DEFAULT NULL, nbpartenaire INT DEFAULT NULL, nbecole INT DEFAULT NULL, date DATE DEFAULT NULL, INDEX fk_sejou_idx (idsejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cliparpage (id INT AUTO_INCREMENT NOT NULL, idpage INT DEFAULT NULL, idclipart INT DEFAULT NULL, styleclipart VARCHAR(255) DEFAULT NULL, taille VARCHAR(255) DEFAULT NULL, INDEX fk_clipart_page_idx (idclipart), INDEX fk_photo_clipart_idx (idpage), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clipart (id INT AUTO_INCREMENT NOT NULL, path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comande_produit (id INT AUTO_INCREMENT NOT NULL, id_comande INT DEFAULT NULL, id_produit INT DEFAULT NULL, quantiter INT DEFAULT NULL, reversement NUMERIC(10, 0) DEFAULT NULL, date DATE DEFAULT NULL, pourcentage INT DEFAULT NULL, INDEX IdCommand_idx (id_comande), INDEX IdProduit_idx (id_produit), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande (id INT AUTO_INCREMENT NOT NULL, id_sejour INT DEFAULT NULL, id_user INT DEFAULT NULL, statut INT DEFAULT NULL, adresslivraison INT DEFAULT NULL, adressfactoration INT DEFAULT NULL, id_promotion_id INT DEFAULT NULL, log_promo_id INT DEFAULT NULL, num_comande INT DEFAULT NULL, montantHt DOUBLE PRECISION DEFAULT NULL, montanenv DOUBLE PRECISION DEFAULT NULL, montantRth DOUBLE PRECISION DEFAULT NULL, traiter INT DEFAULT NULL, moantantTtcregl DOUBLE PRECISION DEFAULT NULL, tva NUMERIC(10, 0) DEFAULT NULL, date_create_commande DATE DEFAULT NULL, date_facture DATE DEFAULT NULL, Jeton INT DEFAULT NULL, payement_type VARCHAR(255) DEFAULT NULL, periode VARCHAR(255) DEFAULT NULL, dupligetStatut VARCHAR(255) DEFAULT NULL, revesmentpart DOUBLE PRECISION DEFAULT NULL, remisecodepromo DOUBLE PRECISION DEFAULT NULL, totalBlackFriday DOUBLE PRECISION DEFAULT NULL, nbconnx INT DEFAULT NULL, rev INT DEFAULT NULL, NumSuivi VARCHAR(255) DEFAULT NULL, dateLivraison DATE DEFAULT NULL, dateExpidition DATE DEFAULT NULL, lettreSuivi VARCHAR(255) DEFAULT NULL, addresseLivraison VARCHAR(255) DEFAULT NULL, nbenfantencours INT DEFAULT NULL, numfacture INT DEFAULT NULL, idPanier_id INT DEFAULT NULL, INDEX IDX_6EEAA67DB0C295C5 (id_sejour), INDEX IDX_6EEAA67DE985CED1 (adresslivraison), INDEX IDX_6EEAA67D9D504691 (adressfactoration), INDEX IDX_6EEAA67DB97B92A (idPanier_id), INDEX IDX_6EEAA67D305C84E6 (id_promotion_id), INDEX IDX_6EEAA67DBE93B120 (log_promo_id), INDEX fk_Commandestatut_idx (statut), INDEX fkuser_idx (id_user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_numerique (id INT AUTO_INCREMENT NOT NULL, id_commande_id INT DEFAULT NULL, date_creation DATETIME DEFAULT NULL, linkdownload LONGTEXT DEFAULT NULL, etat INT DEFAULT NULL, date_telechargement DATETIME DEFAULT NULL, envoi INT DEFAULT NULL, INDEX IDX_CBD329C79AF8E3A3 (id_commande_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commentaire (id INT AUTO_INCREMENT NOT NULL, id_attchment_sejour INT DEFAULT NULL, labele_commtaire VARCHAR(45) DEFAULT NULL, date_com DATE DEFAULT NULL, Id_user INT DEFAULT NULL, INDEX fk_usr_idx (Id_user), INDEX fk_attch_sej (id_attchment_sejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commentaire_etiquette (id INT AUTO_INCREMENT NOT NULL, createur_id INT DEFAULT NULL, etiquette_id INT DEFAULT NULL, text LONGTEXT DEFAULT NULL, statut VARCHAR(45) DEFAULT NULL, typecommentaire VARCHAR(45) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, INDEX IDX_9199966D73A201E5 (createur_id), INDEX IDX_9199966D7BD2EA57 (etiquette_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comptebancaire (id INT AUTO_INCREMENT NOT NULL, codebnaque VARCHAR(255) DEFAULT NULL, codeguichet VARCHAR(255) DEFAULT NULL, numcompt VARCHAR(255) DEFAULT NULL, clerib VARCHAR(255) DEFAULT NULL, iban VARCHAR(255) DEFAULT NULL, codebic VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, domicilation VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documentpartenaire (id INT AUTO_INCREMENT NOT NULL, idetablisment INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, nomdocument VARCHAR(255) DEFAULT NULL, INDEX IDX_6D5B2ACF5C68DBFF (idetablisment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE emailing (id INT AUTO_INCREMENT NOT NULL, typeemail INT DEFAULT NULL, id_user_creation INT DEFAULT NULL, id_image1 INT DEFAULT NULL, id_image2 INT DEFAULT NULL, statut INT DEFAULT NULL, id_destinataire INT DEFAULT NULL, date_creation DATE NOT NULL, INDEX fk_emailing_creator (id_user_creation), INDEX fk_emailing_image2 (id_image2), INDEX fk_emailing_typeemail (typeemail), INDEX fk_email_user (id_destinataire), INDEX fk_emailing_image1 (id_image1), INDEX fk_emailing_statut (statut), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE emailrelance (id INT AUTO_INCREMENT NOT NULL, dateCreation DATETIME DEFAULT NULL, dateSend DATETIME DEFAULT NULL, flagdepot INT DEFAULT NULL, sendTo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE emails_sejours_en_masse (id INT AUTO_INCREMENT NOT NULL, id_accompagnateur INT DEFAULT NULL, email_acco VARCHAR(255) DEFAULT NULL, password_acco VARCHAR(255) DEFAULT NULL, id_sejour INT DEFAULT NULL, type_sejour VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, date_envoi DATE DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etablisment (id INT AUTO_INCREMENT NOT NULL, nometab VARCHAR(45) DEFAULT NULL, codepostaleatb INT DEFAULT NULL, nomcon VARCHAR(45) DEFAULT NULL, typeetablisment VARCHAR(45) DEFAULT NULL, formatEtablisement VARCHAR(100) DEFAULT NULL, numRCS VARCHAR(100) DEFAULT NULL, prenomcont VARCHAR(45) DEFAULT NULL, fonctioncontact VARCHAR(45) DEFAULT NULL, numerotelp VARCHAR(45) DEFAULT NULL, email VARCHAR(45) DEFAULT NULL, adresseetab VARCHAR(45) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, ville VARCHAR(45) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, prixcnxparent DOUBLE PRECISION DEFAULT NULL, prixcnxpartenaire DOUBLE PRECISION DEFAULT NULL, reversecnxpart DOUBLE PRECISION DEFAULT NULL, reverseventepart DOUBLE PRECISION DEFAULT NULL, delated INT DEFAULT NULL, User_id INT DEFAULT NULL, INDEX fk_Ecole_User1_idx (User_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etiquette (id INT AUTO_INCREMENT NOT NULL, support_id INT DEFAULT NULL, rapporteur_id INT DEFAULT NULL, titre VARCHAR(255) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, INDEX IDX_1E0E195A315B405 (support_id), INDEX IDX_1E0E195A2AF5D182 (rapporteur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fonctions (id INT AUTO_INCREMENT NOT NULL, statut_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, INDEX IDX_AED700EFF6203804 (statut_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE jourdescripdate (id INT AUTO_INCREMENT NOT NULL, idsejour INT DEFAULT NULL, description LONGTEXT DEFAULT NULL, datejourphoto DATE DEFAULT NULL, INDEX FK_218C35CEF2488D84 (idsejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE likephoto (id INT AUTO_INCREMENT NOT NULL, id_sejour_attchment INT DEFAULT NULL, id_produit INT DEFAULT NULL, id_user INT DEFAULT NULL, date DATE DEFAULT NULL, etat VARCHAR(45) DEFAULT NULL, id_sejour INT DEFAULT NULL, INDEX fk_likeprodiut_idx (id_produit), INDEX fk_userlike_idx (id_user), INDEX fk_likesejourAttach_idx (id_sejour_attchment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log_promotions (id INT AUTO_INCREMENT NOT NULL, id_commande_id INT DEFAULT NULL, id_client_id INT DEFAULT NULL, id_promotion_id INT DEFAULT NULL, date_creation DATETIME DEFAULT NULL, INDEX IDX_E00D9C8F9AF8E3A3 (id_commande_id), INDEX IDX_E00D9C8F99DED506 (id_client_id), INDEX IDX_E00D9C8F305C84E6 (id_promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE migration_versions (version VARCHAR(14) NOT NULL, executed_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, idtypepage INT DEFAULT NULL, idproduit INT DEFAULT NULL, pagesuivante INT DEFAULT NULL, pageprecedente INT DEFAULT NULL, couleurbordure TINYTEXT DEFAULT NULL, INDEX fk_typpage_idx (idtypepage), INDEX fk_produit_page_idx (idproduit), INDEX fk_pagesuivante_idx (pagesuivante), INDEX fk_pageprecedente_idx (pageprecedente), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE panier (id INT AUTO_INCREMENT NOT NULL, statut_id INT DEFAULT NULL, dateCreation DATE DEFAULT NULL, prixTotal DOUBLE PRECISION DEFAULT NULL, numPanier VARCHAR(255) DEFAULT NULL, Jeton INT DEFAULT NULL, creerPar_id INT DEFAULT NULL, idSejour_id INT DEFAULT NULL, INDEX IDX_24CC0DF2F6203804 (statut_id), INDEX IDX_24CC0DF255EF9D79 (creerPar_id), INDEX IDX_24CC0DF2F4A6DB99 (idSejour_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE panierproduit (id INT AUTO_INCREMENT NOT NULL, prixTotal INT DEFAULT NULL, quantite INT DEFAULT NULL, idProduit_id INT DEFAULT NULL, idPanier_id INT DEFAULT NULL, INDEX IDX_656FE9BA8DC06011 (idProduit_id), INDEX IDX_656FE9BAB97B92A (idPanier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parent_sejour (id INT AUTO_INCREMENT NOT NULL, id_parent INT DEFAULT NULL, date_creation DATE DEFAULT NULL, date_modification DATE DEFAULT NULL, payment INT DEFAULT NULL, smsnotif INT DEFAULT NULL, mailnotif INT DEFAULT NULL, traiter INT DEFAULT NULL, rev INT DEFAULT NULL, fact INT DEFAULT NULL, flagPrix INT DEFAULT NULL, Id_sejour INT DEFAULT NULL, INDEX fk_sejour_user_idx (id_parent), INDEX Id_Sjour_idx (Id_sejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE photonsumeriques (id INT AUTO_INCREMENT NOT NULL, id_sejour_id INT DEFAULT NULL, id_user_id INT DEFAULT NULL, id_sejour_attachement_id INT DEFAULT NULL, id_produit_id INT DEFAULT NULL, date_creation DATETIME DEFAULT NULL, INDEX IDX_F1D7175B88794CE8 (id_sejour_id), INDEX IDX_F1D7175B79F37AE5 (id_user_id), INDEX IDX_F1D7175BA3E01CD2 (id_sejour_attachement_id), INDEX IDX_F1D7175BAABEFE2C (id_produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE position (id INT AUTO_INCREMENT NOT NULL, idcart INT DEFAULT NULL, nom_position VARCHAR(45) DEFAULT NULL, rue_position VARCHAR(45) DEFAULT NULL, num_position VARCHAR(45) DEFAULT NULL, ville_position VARCHAR(45) DEFAULT NULL, lat_position VARCHAR(45) DEFAULT NULL, lng_position VARCHAR(45) DEFAULT NULL, postal VARCHAR(45) DEFAULT NULL, pays_position VARCHAR(45) DEFAULT NULL, date_position DATE DEFAULT NULL, Iduser INT DEFAULT NULL, INDEX fk_Positioncart_idx (idcart), INDEX fk_Position_1_idx (Iduser), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit (id INT AUTO_INCREMENT NOT NULL, idsjour INT DEFAULT NULL, type INT DEFAULT NULL, iduser INT DEFAULT NULL, labele VARCHAR(45) DEFAULT NULL, prix INT DEFAULT NULL, Produitcol VARCHAR(45) DEFAULT NULL, date DATETIME DEFAULT NULL, statut VARCHAR(45) DEFAULT NULL, nbattach INT DEFAULT NULL, pathpdf LONGTEXT DEFAULT NULL, delated INT DEFAULT NULL, version VARCHAR(45) DEFAULT NULL, idConditionnement_id INT DEFAULT NULL, INDEX IDX_29A5EC276AF640F0 (idConditionnement_id), INDEX fk_produittype_idx (type), INDEX fk_user_idx (iduser), INDEX fk_Produitsjour_idx (idsjour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit_attachement (id INT AUTO_INCREMENT NOT NULL, id_produit INT DEFAULT NULL, id_attachement INT DEFAULT NULL, date DATETIME DEFAULT NULL, INDEX fk_attachement_pr_idx (id_attachement), INDEX fk_produit_at_idx (id_produit), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promo_parents (id INT AUTO_INCREMENT NOT NULL, promotion_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, date_creation DATETIME DEFAULT NULL, INDEX IDX_F524A558139DF194 (promotion_id), INDEX IDX_F524A558727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promo_sejour (id INT AUTO_INCREMENT NOT NULL, promotion_id INT DEFAULT NULL, sejour_id INT NOT NULL, date_creation DATETIME DEFAULT NULL, INDEX IDX_8F703F65139DF194 (promotion_id), INDEX IDX_8F703F6584CF0CF (sejour_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotions (id INT AUTO_INCREMENT NOT NULL, statut_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, nbre_max_general INT DEFAULT NULL, nbre_max_par_user INT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, etat TINYINT(1) DEFAULT NULL, pourcentage INT DEFAULT NULL, strategie VARCHAR(255) DEFAULT NULL, nbre_applicable INT DEFAULT NULL, INDEX IDX_EA1B3034F6203804 (statut_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ref (id INT AUTO_INCREMENT NOT NULL, typeref INT DEFAULT NULL, libiller VARCHAR(45) DEFAULT NULL, code VARCHAR(45) DEFAULT NULL, INDEX fk_reftype_idx (typeref), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reversement (id INT AUTO_INCREMENT NOT NULL, id_partenaire INT DEFAULT NULL, id_typeproduit INT DEFAULT NULL, reversement INT NOT NULL, date_creation DATE NOT NULL, INDEX fk_reversement_typeproduit (id_typeproduit), INDEX fk_reversement_partenaire (id_partenaire), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sejour (id INT AUTO_INCREMENT NOT NULL, id_etablisment INT DEFAULT NULL, id_partenaire INT DEFAULT NULL, statut INT DEFAULT NULL, age_group INT DEFAULT NULL, code_sejour VARCHAR(45) DEFAULT NULL, date_creation_code DATE DEFAULT NULL, date_fin_code DATE DEFAULT NULL, them_sejour VARCHAR(45) DEFAULT NULL, adresse_sejour VARCHAR(45) DEFAULT NULL, pays VARCHAR(255) DEFAULT NULL, ville VARCHAR(255) DEFAULT NULL, code_postal INT DEFAULT NULL, date_debut_sejour DATE DEFAULT NULL, date_fin_sejour DATE DEFAULT NULL, nb_photo_diposer INT DEFAULT NULL, paym INT DEFAULT NULL, albumgratuie INT DEFAULT NULL, nb_message INT DEFAULT NULL, etat_acomp_Album TINYINT(1) DEFAULT NULL, etat_adresse_carte TINYINT(1) DEFAULT NULL, nbenfan INT DEFAULT NULL, nbenfantencours INT DEFAULT NULL, cd INT DEFAULT NULL, prixcnxparent DOUBLE PRECISION DEFAULT NULL, prixcnxpartenaire DOUBLE PRECISION DEFAULT NULL, reversecnxpart DOUBLE PRECISION DEFAULT NULL, reverseventepart DOUBLE PRECISION DEFAULT NULL, referenc VARCHAR(255) DEFAULT NULL, cp INT DEFAULT NULL, Id_acommp INT DEFAULT NULL, INDEX fk_statu_ref_idx (statut), INDEX fk_userAcomp_idx (Id_acommp), INDEX fk_age_ref_idx (age_group), INDEX fk_userpartenaire_sejour_idx (id_partenaire), INDEX fk_ecole_sejour_idx (id_etablisment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sejour_attachment (id INT AUTO_INCREMENT NOT NULL, id_attchment INT DEFAULT NULL, id_sejour INT DEFAULT NULL, date_depot_attachement DATETIME DEFAULT NULL, etat VARCHAR(45) DEFAULT NULL, nbconsomateurattch INT DEFAULT NULL, nbpartenaireattch INT DEFAULT NULL, nbecoleattch VARCHAR(128) DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, idParent_id INT DEFAULT NULL, INDEX IDX_5C987F228E90E126 (idParent_id), INDEX fk_attchment_idx (id_attchment), INDEX fk_sejour_idx (id_sejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site (id INT AUTO_INCREMENT NOT NULL, user INT DEFAULT NULL, slide1 INT DEFAULT NULL, slide2 INT DEFAULT NULL, slide3 INT DEFAULT NULL, statut INT DEFAULT NULL, code VARCHAR(125) DEFAULT NULL, dateCreation DATE NOT NULL, INDEX fk_site_slide1 (slide1), INDEX fk_site_slide3 (slide3), INDEX fk_site_user (user), INDEX fk_site_slide2 (slide2), INDEX fk_site_statut (statut), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slide (id INT AUTO_INCREMENT NOT NULL, image INT DEFAULT NULL, libele VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX image (image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sms_notif (id INT AUTO_INCREMENT NOT NULL, numbers LONGTEXT DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, date_creat DATETIME DEFAULT NULL, date_send DATETIME DEFAULT NULL, Id_sejour INT DEFAULT NULL, INDEX IDX_42C0D43632331766 (Id_sejour), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_produit_photo (id INT AUTO_INCREMENT NOT NULL, id_attachement INT DEFAULT NULL, id_typep INT DEFAULT NULL, date DATETIME DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, idProduitConditionnement_id INT DEFAULT NULL, INDEX IDX_54C654B9E815D952 (idProduitConditionnement_id), INDEX fk_typep_at_idx (id_attachement, id_typep), INDEX fk_at_typpr (id_typep), INDEX IDX_54C654B9880ED496 (id_attachement), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE typepage (id INT AUTO_INCREMENT NOT NULL, labelle VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE typeproduit (id INT AUTO_INCREMENT NOT NULL, iduser INT DEFAULT NULL, labeleType VARCHAR(255) DEFAULT NULL, caracteristiques LONGTEXT DEFAULT NULL, delais LONGTEXT DEFAULT NULL, tarifs LONGTEXT DEFAULT NULL, traif NUMERIC(10, 0) DEFAULT NULL, fraisDePort NUMERIC(10, 0) DEFAULT NULL, date DATE DEFAULT NULL, description LONGTEXT DEFAULT NULL, plusDescription LONGTEXT DEFAULT NULL, MontantHt INT DEFAULT NULL, MontantTTC INT DEFAULT NULL, PoindsEnGrContenant INT DEFAULT NULL, PoidsEnGrProduit INT DEFAULT NULL, PoidsTotalEnGrHorsPochette INT DEFAULT NULL, PochetteEnvoi INT DEFAULT NULL, statut VARCHAR(255) DEFAULT NULL, reversement DOUBLE PRECISION DEFAULT NULL, INDEX fk_admin_idx (iduser), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE typeproduitconditionnement (id INT AUTO_INCREMENT NOT NULL, montantHT DOUBLE PRECISION DEFAULT NULL, montantTTC DOUBLE PRECISION DEFAULT NULL, TVA DOUBLE PRECISION DEFAULT NULL, poidsContenant INT DEFAULT NULL, poidsProduit INT DEFAULT NULL, poidsTotal INT DEFAULT NULL, pochetteEnvoi INT DEFAULT NULL, descriptionCommande VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, sousTitre VARCHAR(255) DEFAULT NULL, orderprod INT DEFAULT NULL, idTypeProduit_id INT DEFAULT NULL, INDEX IDX_AF8ED7C9652F74B5 (idTypeProduit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE typeref (id INT AUTO_INCREMENT NOT NULL, libiler VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, adresslivraison INT DEFAULT NULL, adressfactoration INT DEFAULT NULL, statut INT DEFAULT NULL, usersecondaire INT DEFAULT NULL, comptebanque INT DEFAULT NULL, id_fonction_id INT DEFAULT NULL, nbconnx VARCHAR(45) DEFAULT NULL, username VARCHAR(45) DEFAULT NULL, adresse VARCHAR(45) DEFAULT NULL, fonction VARCHAR(45) DEFAULT NULL, etablisment VARCHAR(45) DEFAULT NULL, numMobile VARCHAR(255) DEFAULT NULL, logourl LONGTEXT DEFAULT NULL, Datedepart DATE DEFAULT NULL, dateFlagDepot DATE DEFAULT NULL, flagDepot VARCHAR(45) DEFAULT NULL, nom VARCHAR(45) DEFAULT NULL, prenom VARCHAR(45) DEFAULT NULL, roles TINYTEXT DEFAULT NULL, email VARCHAR(45) DEFAULT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(45) DEFAULT NULL, date_creation DATETIME DEFAULT NULL, nometablisment VARCHAR(45) DEFAULT NULL, randomnotice INT DEFAULT NULL, infocomple VARCHAR(45) DEFAULT NULL, reponseemail VARCHAR(255) DEFAULT NULL, password_non_cripted VARCHAR(255) DEFAULT NULL, cnxparent INT DEFAULT NULL, accompaplus VARCHAR(45) DEFAULT NULL, activatemail INT DEFAULT NULL, Jeton INT DEFAULT NULL, showpubprod INT DEFAULT NULL, showdetailsalbum VARCHAR(45) DEFAULT NULL, showdetailslivre VARCHAR(45) DEFAULT NULL, showdetailsphotos VARCHAR(45) DEFAULT NULL, showdetailsretros VARCHAR(45) DEFAULT NULL, showdetailscal VARCHAR(45) DEFAULT NULL, cnxpartenaire INT DEFAULT NULL, smsnotif INT DEFAULT NULL, mailnotif INT DEFAULT NULL, AccoPlusToPartenaire INT DEFAULT NULL, jeton_acco_plus_sejour_gratuit VARCHAR(255) DEFAULT NULL, INDEX IDX_8D93D649E985CED1 (adresslivraison), INDEX IDX_8D93D6499D504691 (adressfactoration), INDEX IDX_8D93D6493CE77466 (usersecondaire), INDEX IDX_8D93D649C22FC0CB (comptebanque), INDEX IDX_8D93D6494F9A54D7 (id_fonction_id), INDEX fk_Userref_idx (statut), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE Element ADD CONSTRAINT FK_8EFD67A57B69AEAF FOREIGN KEY (idclipart) REFERENCES clipart (id)');
        $this->addSql('ALTER TABLE Element ADD CONSTRAINT FK_8EFD67A5E8445667 FOREIGN KEY (idtext) REFERENCES blocktext (id)');
        $this->addSql('ALTER TABLE Element ADD CONSTRAINT FK_8EFD67A5C7C54780 FOREIGN KEY (idpage) REFERENCES page (id)');
        $this->addSql('ALTER TABLE PageBlocktexte ADD CONSTRAINT FK_85E1E154C7C54780 FOREIGN KEY (idpage) REFERENCES page (id)');
        $this->addSql('ALTER TABLE PageBlocktexte ADD CONSTRAINT FK_85E1E1546A70DEF2 FOREIGN KEY (idblocktext) REFERENCES blocktext (id)');
        $this->addSql('ALTER TABLE Pageattachement ADD CONSTRAINT FK_7072E619B4F6C481 FOREIGN KEY (idattachment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE Pageattachement ADD CONSTRAINT FK_7072E619C7C54780 FOREIGN KEY (idpage) REFERENCES page (id)');
        $this->addSql('ALTER TABLE attachement_etiquette ADD CONSTRAINT FK_A908717B58139F25 FOREIGN KEY (id_etiquette_id) REFERENCES etiquette (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBECF9ACF8 FOREIGN KEY (idposition) REFERENCES position (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBD6A65C4 FOREIGN KEY (idref) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB5E5C27E9 FOREIGN KEY (iduser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog ADD CONSTRAINT FK_C0155143E564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE blog ADD CONSTRAINT FK_C01551435E5C27E9 FOREIGN KEY (iduser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_attachement ADD CONSTRAINT FK_492C859F13DAA0E3 FOREIGN KEY (idblog) REFERENCES blog (id)');
        $this->addSql('ALTER TABLE blog_attachement ADD CONSTRAINT FK_492C859F56DD69CE FOREIGN KEY (idattachement) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE bolt_pages ADD CONSTRAINT FK_31AF1BC8497DD634 FOREIGN KEY (categorie) REFERENCES bolt_taxonomy (id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7F2488D84 FOREIGN KEY (idsejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE cliparpage ADD CONSTRAINT FK_3535C862C7C54780 FOREIGN KEY (idpage) REFERENCES page (id)');
        $this->addSql('ALTER TABLE cliparpage ADD CONSTRAINT FK_3535C8627B69AEAF FOREIGN KEY (idclipart) REFERENCES clipart (id)');
        $this->addSql('ALTER TABLE comande_produit ADD CONSTRAINT FK_506482099C35633D FOREIGN KEY (id_comande) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE comande_produit ADD CONSTRAINT FK_50648209F7384557 FOREIGN KEY (id_produit) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DB0C295C5 FOREIGN KEY (id_sejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DE564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DE985CED1 FOREIGN KEY (adresslivraison) REFERENCES adress (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D9D504691 FOREIGN KEY (adressfactoration) REFERENCES adress (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DB97B92A FOREIGN KEY (idPanier_id) REFERENCES panier (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D305C84E6 FOREIGN KEY (id_promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DBE93B120 FOREIGN KEY (log_promo_id) REFERENCES log_promotions (id)');
        $this->addSql('ALTER TABLE commande_numerique ADD CONSTRAINT FK_CBD329C79AF8E3A3 FOREIGN KEY (id_commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC9803E4E7 FOREIGN KEY (id_attchment_sejour) REFERENCES sejour_attachment (id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCC90EF3D7 FOREIGN KEY (Id_user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE commentaire_etiquette ADD CONSTRAINT FK_9199966D73A201E5 FOREIGN KEY (createur_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE commentaire_etiquette ADD CONSTRAINT FK_9199966D7BD2EA57 FOREIGN KEY (etiquette_id) REFERENCES etiquette (id)');
        $this->addSql('ALTER TABLE documentpartenaire ADD CONSTRAINT FK_6D5B2ACF5C68DBFF FOREIGN KEY (idetablisment) REFERENCES etablisment (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F966DB8C967 FOREIGN KEY (typeemail) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F9694BB011 FOREIGN KEY (id_user_creation) REFERENCES user (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F965EFA2B3B FOREIGN KEY (id_image1) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F96C7F37A81 FOREIGN KEY (id_image2) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F96E564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE emailing ADD CONSTRAINT FK_5E9C9F96DD688AE0 FOREIGN KEY (id_destinataire) REFERENCES user (id)');
        $this->addSql('ALTER TABLE etablisment ADD CONSTRAINT FK_9AA9AB5068D3EA09 FOREIGN KEY (User_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE etiquette ADD CONSTRAINT FK_1E0E195A315B405 FOREIGN KEY (support_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE etiquette ADD CONSTRAINT FK_1E0E195A2AF5D182 FOREIGN KEY (rapporteur_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE fonctions ADD CONSTRAINT FK_AED700EFF6203804 FOREIGN KEY (statut_id) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE jourdescripdate ADD CONSTRAINT FK_218C35CEF2488D84 FOREIGN KEY (idsejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE likephoto ADD CONSTRAINT FK_90E7287DDAB61219 FOREIGN KEY (id_sejour_attchment) REFERENCES sejour_attachment (id)');
        $this->addSql('ALTER TABLE likephoto ADD CONSTRAINT FK_90E7287DF7384557 FOREIGN KEY (id_produit) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE likephoto ADD CONSTRAINT FK_90E7287D6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log_promotions ADD CONSTRAINT FK_E00D9C8F9AF8E3A3 FOREIGN KEY (id_commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE log_promotions ADD CONSTRAINT FK_E00D9C8F99DED506 FOREIGN KEY (id_client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log_promotions ADD CONSTRAINT FK_E00D9C8F305C84E6 FOREIGN KEY (id_promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620F1A30136 FOREIGN KEY (idtypepage) REFERENCES typepage (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB620F6A1BE49 FOREIGN KEY (idproduit) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62099B4A8EA FOREIGN KEY (pagesuivante) REFERENCES page (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62093006792 FOREIGN KEY (pageprecedente) REFERENCES page (id)');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2F6203804 FOREIGN KEY (statut_id) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF255EF9D79 FOREIGN KEY (creerPar_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2F4A6DB99 FOREIGN KEY (idSejour_id) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE panierproduit ADD CONSTRAINT FK_656FE9BA8DC06011 FOREIGN KEY (idProduit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE panierproduit ADD CONSTRAINT FK_656FE9BAB97B92A FOREIGN KEY (idPanier_id) REFERENCES panier (id)');
        $this->addSql('ALTER TABLE parent_sejour ADD CONSTRAINT FK_D9E6E3EE1BB9D5A2 FOREIGN KEY (id_parent) REFERENCES user (id)');
        $this->addSql('ALTER TABLE parent_sejour ADD CONSTRAINT FK_D9E6E3EE32331766 FOREIGN KEY (Id_sejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE photonsumeriques ADD CONSTRAINT FK_F1D7175B88794CE8 FOREIGN KEY (id_sejour_id) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE photonsumeriques ADD CONSTRAINT FK_F1D7175B79F37AE5 FOREIGN KEY (id_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE photonsumeriques ADD CONSTRAINT FK_F1D7175BA3E01CD2 FOREIGN KEY (id_sejour_attachement_id) REFERENCES sejour_attachment (id)');
        $this->addSql('ALTER TABLE photonsumeriques ADD CONSTRAINT FK_F1D7175BAABEFE2C FOREIGN KEY (id_produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F5D86C7917 FOREIGN KEY (idcart) REFERENCES cart (id)');
        $this->addSql('ALTER TABLE position ADD CONSTRAINT FK_462CE4F559F022DF FOREIGN KEY (Iduser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27550607C2 FOREIGN KEY (idsjour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC278CDE5729 FOREIGN KEY (type) REFERENCES typeproduit (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC275E5C27E9 FOREIGN KEY (iduser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC276AF640F0 FOREIGN KEY (idConditionnement_id) REFERENCES typeproduitconditionnement (id)');
        $this->addSql('ALTER TABLE produit_attachement ADD CONSTRAINT FK_EE045DE5F7384557 FOREIGN KEY (id_produit) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE produit_attachement ADD CONSTRAINT FK_EE045DE5880ED496 FOREIGN KEY (id_attachement) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE promo_parents ADD CONSTRAINT FK_F524A558139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE promo_parents ADD CONSTRAINT FK_F524A558727ACA70 FOREIGN KEY (parent_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE promo_sejour ADD CONSTRAINT FK_8F703F65139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE promo_sejour ADD CONSTRAINT FK_8F703F6584CF0CF FOREIGN KEY (sejour_id) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B3034F6203804 FOREIGN KEY (statut_id) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE ref ADD CONSTRAINT FK_146F3EA3B7627700 FOREIGN KEY (typeref) REFERENCES typeref (id)');
        $this->addSql('ALTER TABLE reversement ADD CONSTRAINT FK_6D601223977523A4 FOREIGN KEY (id_partenaire) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reversement ADD CONSTRAINT FK_6D601223EB53AD6B FOREIGN KEY (id_typeproduit) REFERENCES typeproduit (id)');
        $this->addSql('ALTER TABLE sejour ADD CONSTRAINT FK_96F5202882BB66A7 FOREIGN KEY (id_etablisment) REFERENCES etablisment (id)');
        $this->addSql('ALTER TABLE sejour ADD CONSTRAINT FK_96F52028AB229C7F FOREIGN KEY (Id_acommp) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sejour ADD CONSTRAINT FK_96F52028977523A4 FOREIGN KEY (id_partenaire) REFERENCES user (id)');
        $this->addSql('ALTER TABLE sejour ADD CONSTRAINT FK_96F52028E564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE sejour ADD CONSTRAINT FK_96F52028F88B4253 FOREIGN KEY (age_group) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE sejour_attachment ADD CONSTRAINT FK_5C987F22117DC25D FOREIGN KEY (id_attchment) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE sejour_attachment ADD CONSTRAINT FK_5C987F22B0C295C5 FOREIGN KEY (id_sejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE sejour_attachment ADD CONSTRAINT FK_5C987F228E90E126 FOREIGN KEY (idParent_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E48D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E42012002D FOREIGN KEY (slide1) REFERENCES slide (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4B91B5197 FOREIGN KEY (slide2) REFERENCES slide (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4CE1C6101 FOREIGN KEY (slide3) REFERENCES slide (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4E564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE slide ADD CONSTRAINT FK_72EFEE62C53D045F FOREIGN KEY (image) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE sms_notif ADD CONSTRAINT FK_42C0D43632331766 FOREIGN KEY (Id_sejour) REFERENCES sejour (id)');
        $this->addSql('ALTER TABLE type_produit_photo ADD CONSTRAINT FK_54C654B9880ED496 FOREIGN KEY (id_attachement) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE type_produit_photo ADD CONSTRAINT FK_54C654B92EBC99BA FOREIGN KEY (id_typep) REFERENCES typeproduit (id)');
        $this->addSql('ALTER TABLE type_produit_photo ADD CONSTRAINT FK_54C654B9E815D952 FOREIGN KEY (idProduitConditionnement_id) REFERENCES typeproduitconditionnement (id)');
        $this->addSql('ALTER TABLE typeproduit ADD CONSTRAINT FK_F341609C5E5C27E9 FOREIGN KEY (iduser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeproduitconditionnement ADD CONSTRAINT FK_AF8ED7C9652F74B5 FOREIGN KEY (idTypeProduit_id) REFERENCES typeproduit (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E985CED1 FOREIGN KEY (adresslivraison) REFERENCES adress (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6499D504691 FOREIGN KEY (adressfactoration) REFERENCES adress (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E564F0BF FOREIGN KEY (statut) REFERENCES ref (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6493CE77466 FOREIGN KEY (usersecondaire) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649C22FC0CB FOREIGN KEY (comptebanque) REFERENCES comptebancaire (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6494F9A54D7 FOREIGN KEY (id_fonction_id) REFERENCES fonctions (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Element DROP FOREIGN KEY FK_8EFD67A57B69AEAF');
        $this->addSql('ALTER TABLE Element DROP FOREIGN KEY FK_8EFD67A5E8445667');
        $this->addSql('ALTER TABLE Element DROP FOREIGN KEY FK_8EFD67A5C7C54780');
        $this->addSql('ALTER TABLE PageBlocktexte DROP FOREIGN KEY FK_85E1E154C7C54780');
        $this->addSql('ALTER TABLE PageBlocktexte DROP FOREIGN KEY FK_85E1E1546A70DEF2');
        $this->addSql('ALTER TABLE Pageattachement DROP FOREIGN KEY FK_7072E619B4F6C481');
        $this->addSql('ALTER TABLE Pageattachement DROP FOREIGN KEY FK_7072E619C7C54780');
        $this->addSql('ALTER TABLE attachement_etiquette DROP FOREIGN KEY FK_A908717B58139F25');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BBECF9ACF8');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BBD6A65C4');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BB5E5C27E9');
        $this->addSql('ALTER TABLE blog DROP FOREIGN KEY FK_C0155143E564F0BF');
        $this->addSql('ALTER TABLE blog DROP FOREIGN KEY FK_C01551435E5C27E9');
        $this->addSql('ALTER TABLE blog_attachement DROP FOREIGN KEY FK_492C859F13DAA0E3');
        $this->addSql('ALTER TABLE blog_attachement DROP FOREIGN KEY FK_492C859F56DD69CE');
        $this->addSql('ALTER TABLE bolt_pages DROP FOREIGN KEY FK_31AF1BC8497DD634');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7F2488D84');
        $this->addSql('ALTER TABLE cliparpage DROP FOREIGN KEY FK_3535C862C7C54780');
        $this->addSql('ALTER TABLE cliparpage DROP FOREIGN KEY FK_3535C8627B69AEAF');
        $this->addSql('ALTER TABLE comande_produit DROP FOREIGN KEY FK_506482099C35633D');
        $this->addSql('ALTER TABLE comande_produit DROP FOREIGN KEY FK_50648209F7384557');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DB0C295C5');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D6B3CA4B');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DE564F0BF');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DE985CED1');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D9D504691');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DB97B92A');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D305C84E6');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DBE93B120');
        $this->addSql('ALTER TABLE commande_numerique DROP FOREIGN KEY FK_CBD329C79AF8E3A3');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC9803E4E7');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCC90EF3D7');
        $this->addSql('ALTER TABLE commentaire_etiquette DROP FOREIGN KEY FK_9199966D73A201E5');
        $this->addSql('ALTER TABLE commentaire_etiquette DROP FOREIGN KEY FK_9199966D7BD2EA57');
        $this->addSql('ALTER TABLE documentpartenaire DROP FOREIGN KEY FK_6D5B2ACF5C68DBFF');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F966DB8C967');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F9694BB011');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F965EFA2B3B');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F96C7F37A81');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F96E564F0BF');
        $this->addSql('ALTER TABLE emailing DROP FOREIGN KEY FK_5E9C9F96DD688AE0');
        $this->addSql('ALTER TABLE etablisment DROP FOREIGN KEY FK_9AA9AB5068D3EA09');
        $this->addSql('ALTER TABLE etiquette DROP FOREIGN KEY FK_1E0E195A315B405');
        $this->addSql('ALTER TABLE etiquette DROP FOREIGN KEY FK_1E0E195A2AF5D182');
        $this->addSql('ALTER TABLE fonctions DROP FOREIGN KEY FK_AED700EFF6203804');
        $this->addSql('ALTER TABLE jourdescripdate DROP FOREIGN KEY FK_218C35CEF2488D84');
        $this->addSql('ALTER TABLE likephoto DROP FOREIGN KEY FK_90E7287DDAB61219');
        $this->addSql('ALTER TABLE likephoto DROP FOREIGN KEY FK_90E7287DF7384557');
        $this->addSql('ALTER TABLE likephoto DROP FOREIGN KEY FK_90E7287D6B3CA4B');
        $this->addSql('ALTER TABLE log_promotions DROP FOREIGN KEY FK_E00D9C8F9AF8E3A3');
        $this->addSql('ALTER TABLE log_promotions DROP FOREIGN KEY FK_E00D9C8F99DED506');
        $this->addSql('ALTER TABLE log_promotions DROP FOREIGN KEY FK_E00D9C8F305C84E6');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB620F1A30136');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB620F6A1BE49');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB62099B4A8EA');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB62093006792');
        $this->addSql('ALTER TABLE panier DROP FOREIGN KEY FK_24CC0DF2F6203804');
        $this->addSql('ALTER TABLE panier DROP FOREIGN KEY FK_24CC0DF255EF9D79');
        $this->addSql('ALTER TABLE panier DROP FOREIGN KEY FK_24CC0DF2F4A6DB99');
        $this->addSql('ALTER TABLE panierproduit DROP FOREIGN KEY FK_656FE9BA8DC06011');
        $this->addSql('ALTER TABLE panierproduit DROP FOREIGN KEY FK_656FE9BAB97B92A');
        $this->addSql('ALTER TABLE parent_sejour DROP FOREIGN KEY FK_D9E6E3EE1BB9D5A2');
        $this->addSql('ALTER TABLE parent_sejour DROP FOREIGN KEY FK_D9E6E3EE32331766');
        $this->addSql('ALTER TABLE photonsumeriques DROP FOREIGN KEY FK_F1D7175B88794CE8');
        $this->addSql('ALTER TABLE photonsumeriques DROP FOREIGN KEY FK_F1D7175B79F37AE5');
        $this->addSql('ALTER TABLE photonsumeriques DROP FOREIGN KEY FK_F1D7175BA3E01CD2');
        $this->addSql('ALTER TABLE photonsumeriques DROP FOREIGN KEY FK_F1D7175BAABEFE2C');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F5D86C7917');
        $this->addSql('ALTER TABLE position DROP FOREIGN KEY FK_462CE4F559F022DF');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC27550607C2');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC278CDE5729');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC275E5C27E9');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC276AF640F0');
        $this->addSql('ALTER TABLE produit_attachement DROP FOREIGN KEY FK_EE045DE5F7384557');
        $this->addSql('ALTER TABLE produit_attachement DROP FOREIGN KEY FK_EE045DE5880ED496');
        $this->addSql('ALTER TABLE promo_parents DROP FOREIGN KEY FK_F524A558139DF194');
        $this->addSql('ALTER TABLE promo_parents DROP FOREIGN KEY FK_F524A558727ACA70');
        $this->addSql('ALTER TABLE promo_sejour DROP FOREIGN KEY FK_8F703F65139DF194');
        $this->addSql('ALTER TABLE promo_sejour DROP FOREIGN KEY FK_8F703F6584CF0CF');
        $this->addSql('ALTER TABLE promotions DROP FOREIGN KEY FK_EA1B3034F6203804');
        $this->addSql('ALTER TABLE ref DROP FOREIGN KEY FK_146F3EA3B7627700');
        $this->addSql('ALTER TABLE reversement DROP FOREIGN KEY FK_6D601223977523A4');
        $this->addSql('ALTER TABLE reversement DROP FOREIGN KEY FK_6D601223EB53AD6B');
        $this->addSql('ALTER TABLE sejour DROP FOREIGN KEY FK_96F5202882BB66A7');
        $this->addSql('ALTER TABLE sejour DROP FOREIGN KEY FK_96F52028AB229C7F');
        $this->addSql('ALTER TABLE sejour DROP FOREIGN KEY FK_96F52028977523A4');
        $this->addSql('ALTER TABLE sejour DROP FOREIGN KEY FK_96F52028E564F0BF');
        $this->addSql('ALTER TABLE sejour DROP FOREIGN KEY FK_96F52028F88B4253');
        $this->addSql('ALTER TABLE sejour_attachment DROP FOREIGN KEY FK_5C987F22117DC25D');
        $this->addSql('ALTER TABLE sejour_attachment DROP FOREIGN KEY FK_5C987F22B0C295C5');
        $this->addSql('ALTER TABLE sejour_attachment DROP FOREIGN KEY FK_5C987F228E90E126');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E48D93D649');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E42012002D');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E4B91B5197');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E4CE1C6101');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E4E564F0BF');
        $this->addSql('ALTER TABLE slide DROP FOREIGN KEY FK_72EFEE62C53D045F');
        $this->addSql('ALTER TABLE sms_notif DROP FOREIGN KEY FK_42C0D43632331766');
        $this->addSql('ALTER TABLE type_produit_photo DROP FOREIGN KEY FK_54C654B9880ED496');
        $this->addSql('ALTER TABLE type_produit_photo DROP FOREIGN KEY FK_54C654B92EBC99BA');
        $this->addSql('ALTER TABLE type_produit_photo DROP FOREIGN KEY FK_54C654B9E815D952');
        $this->addSql('ALTER TABLE typeproduit DROP FOREIGN KEY FK_F341609C5E5C27E9');
        $this->addSql('ALTER TABLE typeproduitconditionnement DROP FOREIGN KEY FK_AF8ED7C9652F74B5');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E985CED1');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6499D504691');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E564F0BF');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6493CE77466');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649C22FC0CB');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6494F9A54D7');
        $this->addSql('DROP TABLE CommandeComptable');
        $this->addSql('DROP TABLE CommandeFile');
        $this->addSql('DROP TABLE Element');
        $this->addSql('DROP TABLE MessagePartenaire');
        $this->addSql('DROP TABLE PageBlocktexte');
        $this->addSql('DROP TABLE Pageattachement');
        $this->addSql('DROP TABLE adress');
        $this->addSql('DROP TABLE attachement_etiquette');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE blocktext');
        $this->addSql('DROP TABLE blog');
        $this->addSql('DROP TABLE blog_attachement');
        $this->addSql('DROP TABLE bolt_authtoken');
        $this->addSql('DROP TABLE bolt_blocks');
        $this->addSql('DROP TABLE bolt_cron');
        $this->addSql('DROP TABLE bolt_entries');
        $this->addSql('DROP TABLE bolt_field_value');
        $this->addSql('DROP TABLE bolt_homepage');
        $this->addSql('DROP TABLE bolt_log_change');
        $this->addSql('DROP TABLE bolt_log_system');
        $this->addSql('DROP TABLE bolt_pages');
        $this->addSql('DROP TABLE bolt_relations');
        $this->addSql('DROP TABLE bolt_showcases');
        $this->addSql('DROP TABLE bolt_taxonomy');
        $this->addSql('DROP TABLE bolt_users');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE cliparpage');
        $this->addSql('DROP TABLE clipart');
        $this->addSql('DROP TABLE comande_produit');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commande_numerique');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE commentaire_etiquette');
        $this->addSql('DROP TABLE comptebancaire');
        $this->addSql('DROP TABLE documentpartenaire');
        $this->addSql('DROP TABLE emailing');
        $this->addSql('DROP TABLE emailrelance');
        $this->addSql('DROP TABLE emails_sejours_en_masse');
        $this->addSql('DROP TABLE etablisment');
        $this->addSql('DROP TABLE etiquette');
        $this->addSql('DROP TABLE fonctions');
        $this->addSql('DROP TABLE jourdescripdate');
        $this->addSql('DROP TABLE likephoto');
        $this->addSql('DROP TABLE log_promotions');
        $this->addSql('DROP TABLE migration_versions');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE panierproduit');
        $this->addSql('DROP TABLE parent_sejour');
        $this->addSql('DROP TABLE photonsumeriques');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_attachement');
        $this->addSql('DROP TABLE promo_parents');
        $this->addSql('DROP TABLE promo_sejour');
        $this->addSql('DROP TABLE promotions');
        $this->addSql('DROP TABLE ref');
        $this->addSql('DROP TABLE reversement');
        $this->addSql('DROP TABLE sejour');
        $this->addSql('DROP TABLE sejour_attachment');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE slide');
        $this->addSql('DROP TABLE sms_notif');
        $this->addSql('DROP TABLE type_produit_photo');
        $this->addSql('DROP TABLE typepage');
        $this->addSql('DROP TABLE typeproduit');
        $this->addSql('DROP TABLE typeproduitconditionnement');
        $this->addSql('DROP TABLE typeref');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
